version: '3.8'

services:
  node:
    container_name: node-service
    env_file:
      - .env
    build:
      context: .
      target: development
    ports:
      - ${PORT}:${PORT}
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    depends_on:
      - database
  database:
    container_name: postgres-db-service
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DB}
    build: ./database/
    env_file:
      - .env
    volumes:
      - ./typeorm/pgdata:/var/lib/postgresql/data
      - ./typeorm/pg-logs:/var/lib/postgresql/logs
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}

